import type { Project } from "./types"

export const SAMPLE_PROJECTS: Project[] = [
  // Easy Section (12 projects)
  {
    id: "proj-e1",
    name: "Temperature Logger",
    description: "Learn to read temperature sensor data and log it in real-time.",
    difficulty: "Easy",
    section: 1,
    sectionName: "Section 1",
    deviceId: "device-001",
    hidden: false,
    objectives: ["Read sensor data", "Display values", "Understand API calls"],
  },
  {
    id: "proj-e2",
    name: "Humidity Monitor",
    description: "Monitor humidity levels from a connected sensor.",
    difficulty: "Easy",
    section: 1,
    sectionName: "Section 1",
    deviceId: "device-002",
    hidden: false,
    objectives: ["Parse JSON responses", "Update UI", "Handle errors"],
  },
  {
    id: "proj-e3",
    name: "Basic Dashboard",
    description: "Create a simple dashboard showing current sensor readings.",
    difficulty: "Easy",
    section: 1,
    sectionName: "Section 1",
    deviceId: "device-003",
    hidden: false,
    objectives: ["Display multiple values", "Format data", "Add styling"],
  },
  {
    id: "proj-e4",
    name: "Sensor Calibration",
    description: "Calibrate a sensor for accuracy.",
    difficulty: "Easy",
    section: 1,
    sectionName: "Section 1",
    deviceId: "device-004",
    hidden: false,
    objectives: ["Calculate averages", "Store baselines", "Compare values"],
  },
  {
    id: "proj-e5",
    name: "Data Logging Basics",
    description: "Log sensor data over time.",
    difficulty: "Easy",
    section: 1,
    sectionName: "Section 1",
    deviceId: "device-005",
    hidden: false,
    objectives: ["Store data", "Retrieve history", "Display trends"],
  },
  {
    id: "proj-e6",
    name: "Alert System",
    description: "Create alerts when sensor values exceed thresholds.",
    difficulty: "Easy",
    section: 1,
    sectionName: "Section 1",
    deviceId: "device-006",
    hidden: false,
    objectives: ["Set thresholds", "Trigger alerts", "Send notifications"],
  },
  {
    id: "proj-e7",
    name: "Greenhouse Monitor",
    description: "Monitor conditions in a greenhouse.",
    difficulty: "Easy",
    section: 2,
    sectionName: "Section 2",
    deviceId: "device-007",
    hidden: false,
    objectives: ["Multiple sensors", "Combined display", "Status indicators"],
  },
  {
    id: "proj-e8",
    name: "Weather Station Basics",
    description: "Build a basic weather station display.",
    difficulty: "Easy",
    section: 2,
    sectionName: "Section 2",
    deviceId: "device-008",
    hidden: false,
    objectives: ["Temperature", "Humidity", "Conditions"],
  },
  {
    id: "proj-e9",
    name: "Smart Doorbell",
    description: "Detect motion and log events.",
    difficulty: "Easy",
    section: 2,
    sectionName: "Section 2",
    deviceId: "device-009",
    hidden: false,
    objectives: ["Event detection", "Timestamps", "Event history"],
  },
  {
    id: "proj-e10",
    name: "Room Occupancy Detector",
    description: "Detect if a room is occupied.",
    difficulty: "Easy",
    section: 2,
    sectionName: "Section 2",
    deviceId: "device-010",
    hidden: false,
    objectives: ["Sensor readings", "Thresholds", "Status display"],
  },
  {
    id: "proj-e11",
    name: "Light Level Monitor",
    description: "Monitor ambient light levels.",
    difficulty: "Easy",
    section: 2,
    sectionName: "Section 2",
    deviceId: "device-011",
    hidden: false,
    objectives: ["Read light sensor", "Display levels", "Adjust UI"],
  },
  {
    id: "proj-e12",
    name: "Noise Level Detector",
    description: "Detect and measure noise levels.",
    difficulty: "Easy",
    section: 2,
    sectionName: "Section 2",
    deviceId: "device-012",
    hidden: false,
    objectives: ["Audio input", "Level calculation", "Visualization"],
  },
  // Intermediate Section (19 projects)
  {
    id: "proj-i1",
    name: "Real-time Data Dashboard",
    description: "Create a dynamic dashboard with live-updating charts.",
    difficulty: "Intermediate",
    section: 2,
    sectionName: "Section 2",
    deviceId: "device-013",
    hidden: false,
    objectives: ["WebSocket connections", "Chart updates", "Performance"],
  },
  {
    id: "proj-i2",
    name: "Data Aggregation",
    description: "Aggregate data from multiple sensors.",
    difficulty: "Intermediate",
    section: 2,
    sectionName: "Section 2",
    deviceId: "device-014",
    hidden: false,
    objectives: ["Multi-sensor handling", "Data aggregation", "Analytics"],
  },
  {
    id: "proj-i3",
    name: "Time Series Analysis",
    description: "Analyze sensor data over time.",
    difficulty: "Intermediate",
    section: 2,
    sectionName: "Section 2",
    deviceId: "device-015",
    hidden: false,
    objectives: ["Data trends", "Pattern recognition", "Predictions"],
  },
  {
    id: "proj-i4",
    name: "Smart Environmental Control",
    description: "Control devices based on sensor readings.",
    difficulty: "Intermediate",
    section: 2,
    sectionName: "Section 2",
    deviceId: "device-016",
    hidden: false,
    objectives: ["Automation rules", "Device control", "Feedback loops"],
  },
  {
    id: "proj-i5",
    name: "Advanced Alerting",
    description: "Create sophisticated alert rules.",
    difficulty: "Intermediate",
    section: 2,
    sectionName: "Section 2",
    deviceId: "device-017",
    hidden: false,
    objectives: ["Complex rules", "Escalation", "Routing"],
  },
  {
    id: "proj-i6",
    name: "Data Export System",
    description: "Export sensor data in multiple formats.",
    difficulty: "Intermediate",
    section: 2,
    sectionName: "Section 2",
    deviceId: "device-018",
    hidden: false,
    objectives: ["CSV export", "JSON formatting", "File download"],
  },
  {
    id: "proj-i7",
    name: "Device Management",
    description: "Manage multiple IoT devices.",
    difficulty: "Intermediate",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-019",
    hidden: false,
    objectives: ["Device registry", "Configuration", "Status monitoring"],
  },
  {
    id: "proj-i8",
    name: "Network Communication",
    description: "Implement device-to-device communication.",
    difficulty: "Intermediate",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-020",
    hidden: false,
    objectives: ["Protocol handling", "Message routing", "Reliability"],
  },
  {
    id: "proj-i9",
    name: "Data Storage Optimization",
    description: "Optimize storage for large datasets.",
    difficulty: "Intermediate",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-021",
    hidden: false,
    objectives: ["Indexing", "Compression", "Query optimization"],
  },
  {
    id: "proj-i10",
    name: "API Rate Limiting",
    description: "Implement rate limiting for API calls.",
    difficulty: "Intermediate",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-022",
    hidden: false,
    objectives: ["Throttling", "Queue management", "Error handling"],
  },
  {
    id: "proj-i11",
    name: "Authentication & Authorization",
    description: "Secure device access with auth.",
    difficulty: "Intermediate",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-023",
    hidden: false,
    objectives: ["Token management", "Permissions", "Audit logging"],
  },
  {
    id: "proj-i12",
    name: "Firmware Updates",
    description: "Implement OTA firmware updates.",
    difficulty: "Intermediate",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-024",
    hidden: false,
    objectives: ["Version control", "Rollback", "Progress tracking"],
  },
  {
    id: "proj-i13",
    name: "Edge Computing",
    description: "Process data at the edge.",
    difficulty: "Intermediate",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-025",
    hidden: false,
    objectives: ["Local processing", "Bandwidth optimization", "Latency reduction"],
  },
  {
    id: "proj-i14",
    name: "Cloud Integration",
    description: "Connect IoT devices to cloud services.",
    difficulty: "Intermediate",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-026",
    hidden: false,
    objectives: ["Cloud APIs", "Data sync", "Hybrid architecture"],
  },
  {
    id: "proj-i15",
    name: "Mobile Dashboard",
    description: "Create a mobile app dashboard.",
    difficulty: "Intermediate",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-027",
    hidden: false,
    objectives: ["Responsive design", "Mobile optimization", "Touch controls"],
  },
  {
    id: "proj-i16",
    name: "Data Visualization",
    description: "Advanced data visualization techniques.",
    difficulty: "Intermediate",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-028",
    hidden: false,
    objectives: ["Charts", "Graphs", "Interactive elements"],
  },
  {
    id: "proj-i17",
    name: "Performance Monitoring",
    description: "Monitor system performance metrics.",
    difficulty: "Intermediate",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-029",
    hidden: false,
    objectives: ["Metrics collection", "Dashboards", "Alerts"],
  },
  {
    id: "proj-i18",
    name: "Scalability Testing",
    description: "Test system at scale.",
    difficulty: "Intermediate",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-030",
    hidden: false,
    objectives: ["Load testing", "Capacity planning", "Bottleneck analysis"],
  },
  {
    id: "proj-i19",
    name: "Reliability Engineering",
    description: "Build reliable IoT systems.",
    difficulty: "Intermediate",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-031",
    hidden: false,
    objectives: ["Redundancy", "Failover", "Error recovery"],
  },
  // Advanced Section (19 projects)
  {
    id: "proj-a1",
    name: "Machine Learning Integration",
    description: "Apply ML models to sensor data.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-032",
    hidden: false,
    objectives: ["Model training", "Inference", "Optimization"],
  },
  {
    id: "proj-a2",
    name: "Anomaly Detection",
    description: "Detect anomalies in sensor data.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-033",
    hidden: false,
    objectives: ["Statistical analysis", "ML models", "Alert generation"],
  },
  {
    id: "proj-a3",
    name: "Predictive Maintenance",
    description: "Predict device failures.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-034",
    hidden: false,
    objectives: ["Pattern recognition", "Predictions", "Scheduling"],
  },
  {
    id: "proj-a4",
    name: "Distributed Systems",
    description: "Build distributed IoT infrastructure.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-035",
    hidden: false,
    objectives: ["Consistency", "Availability", "Partitioning"],
  },
  {
    id: "proj-a5",
    name: "Security Hardening",
    description: "Secure an IoT deployment.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-036",
    hidden: false,
    objectives: ["Encryption", "Vulnerability scanning", "Compliance"],
  },
  {
    id: "proj-a6",
    name: "Advanced Protocol Implementation",
    description: "Implement custom IoT protocols.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-037",
    hidden: false,
    objectives: ["Protocol design", "Optimization", "Testing"],
  },
  {
    id: "proj-a7",
    name: "Real-time Processing",
    description: "Process streams in real-time.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-038",
    hidden: false,
    objectives: ["Stream processing", "Low latency", "High throughput"],
  },
  {
    id: "proj-a8",
    name: "System Architecture Design",
    description: "Design large-scale IoT systems.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-039",
    hidden: false,
    objectives: ["Architecture patterns", "Scalability", "Trade-offs"],
  },
  {
    id: "proj-a9",
    name: "Blockchain Integration",
    description: "Integrate blockchain for IoT.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-040",
    hidden: false,
    objectives: ["Smart contracts", "Transactions", "Verification"],
  },
  {
    id: "proj-a10",
    name: "5G Connectivity",
    description: "Implement 5G IoT solutions.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-041",
    hidden: false,
    objectives: ["Network optimization", "Latency", "Bandwidth"],
  },
  {
    id: "proj-a11",
    name: "Quantum Computing",
    description: "Explore quantum computing for IoT.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-042",
    hidden: false,
    objectives: ["Quantum algorithms", "Encryption", "Simulation"],
  },
  {
    id: "proj-a12",
    name: "AI-Driven Automation",
    description: "Build intelligent automation systems.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-043",
    hidden: false,
    objectives: ["AI models", "Decision making", "Optimization"],
  },
  {
    id: "proj-a13",
    name: "Environmental Sensing",
    description: "Advanced environmental monitoring.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-044",
    hidden: false,
    objectives: ["Complex sensors", "Data fusion", "Analysis"],
  },
  {
    id: "proj-a14",
    name: "Drone Fleet Management",
    description: "Manage autonomous drone fleets.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-045",
    hidden: false,
    objectives: ["Coordination", "Navigation", "Swarm intelligence"],
  },
  {
    id: "proj-a15",
    name: "Smart City Infrastructure",
    description: "Build smart city systems.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-046",
    hidden: false,
    objectives: ["Multi-system integration", "Citizen services", "Data analysis"],
  },
  {
    id: "proj-a16",
    name: "Industrial IoT",
    description: "Implement industrial IoT solutions.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-047",
    hidden: false,
    objectives: ["Equipment monitoring", "Production optimization", "Safety"],
  },
  {
    id: "proj-a17",
    name: "Healthcare IoT",
    description: "Deploy medical IoT systems.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-048",
    hidden: false,
    objectives: ["Patient monitoring", "HIPAA compliance", "Reliability"],
  },
  {
    id: "proj-a18",
    name: "Autonomous Vehicles",
    description: "Develop autonomous vehicle systems.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-049",
    hidden: false,
    objectives: ["Sensor fusion", "Navigation", "Safety systems"],
  },
  {
    id: "proj-a19",
    name: "Enterprise IoT Platform",
    description: "Build enterprise IoT infrastructure.",
    difficulty: "Advanced",
    section: 3,
    sectionName: "Section 3",
    deviceId: "device-050",
    hidden: false,
    objectives: ["Multi-tenancy", "Enterprise features", "Integration"],
  },
]
